<<<<<<< HEAD
import { useEffect, useState } from "react";
import api, { formatApiErrorDetail } from "../../lib/api";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "../../components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "../../components/ui/alert-dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { Plus, Pencil, Trash2, Loader2 } from "lucide-react";
import { toast } from "sonner";
=======
import {useEffect,useState} from "react"; import api,{formatApiErrorDetail} from "../lib/api"; import {Button} from "../components/ui/button"; import {Input} from "../components/ui/input"; import {Label} from "../components/ui/label"; import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter} from "../components/ui/dialog"; import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "../components/ui/alert-dialog"; import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "../components/ui/table"; import {Plus,Pencil,Trash2,Loader2} from "lucide-react"; import {toast} from "sonner";
>>>>>>> 4ae347f (Replace all @/ path aliases with relative paths)
const EMPTY={title:"",author:"",isbn:"",genre:"",publication_year:""};
export default function Books(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[editId,setEditId]=useState(null),[saving,setSaving]=useState(false),[deleteId,setDeleteId]=useState(null);
 const load=async()=>{setLoading(true);try{setItems((await api.get("/books")).data)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setSaving(true);try{const payload={...form,publication_year:form.publication_year?parseInt(form.publication_year,10):null};if(editId){await api.put(`/books/${editId}`,payload);toast.success("Book updated")}else{await api.post("/books",payload);toast.success("Book added")}setOpen(false);load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}finally{setSaving(false)}};
 const del=async()=>{try{await api.delete(`/books/${deleteId}`);toast.success("Book deleted");load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}finally{setDeleteId(null)}};
 return <div><div className="flex items-center justify-between mb-8"><div><p className="text-gold uppercase tracking-widest text-xs mb-2">Manage</p><h1 className="font-serif text-4xl font-bold">Books</h1></div><Button onClick={()=>{setForm(EMPTY);setEditId(null);setOpen(true)}} data-testid="add-book-btn" className="bg-green text-white"><Plus className="w-4 h-4 mr-2"/>Add book</Button></div>
 {loading?<div className="flex gap-2 text-muted"><Loader2 className="animate-spin"/>Loading…</div>:items.length===0?<div className="text-center py-16 border border-dashed border-line text-muted">No books yet. Add your first title.</div>:<div className="border border-line bg-white rounded-sm overflow-hidden"><Table><TableHeader><TableRow className="bg-surface"><TableHead>Title</TableHead><TableHead>Author</TableHead><TableHead className="hidden md:table-cell">Genre</TableHead><TableHead className="hidden md:table-cell">Year</TableHead><TableHead className="hidden lg:table-cell">ISBN</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{items.map(b=><TableRow key={b.id} data-testid="book-row"><TableCell className="py-4 font-medium">{b.title}</TableCell><TableCell className="py-4 text-muted">{b.author}</TableCell><TableCell className="py-4 text-muted hidden md:table-cell">{b.genre||"—"}</TableCell><TableCell className="py-4 text-muted hidden md:table-cell">{b.publication_year||"—"}</TableCell><TableCell className="py-4 text-muted hidden lg:table-cell">{b.isbn||"—"}</TableCell><TableCell className="py-4 text-right"><button onClick={()=>{setForm({title:b.title,author:b.author,isbn:b.isbn||"",genre:b.genre||"",publication_year:b.publication_year||""});setEditId(b.id);setOpen(true)}} data-testid="edit-book-btn" className="p-1.5 text-green"><Pencil className="w-4 h-4"/></button><button onClick={()=>setDeleteId(b.id)} data-testid="delete-book-btn" className="p-1.5 text-[#9A2B2B]"><Trash2 className="w-4 h-4"/></button></TableCell></TableRow>)}</TableBody></Table></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">{editId?"Edit book":"Add book"}</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div><Label>Title</Label><Input className="mt-1.5" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required data-testid="book-title-input"/></div><div><Label>Author</Label><Input className="mt-1.5" value={form.author} onChange={e=>setForm({...form,author:e.target.value})} required data-testid="book-author-input"/></div><div className="grid grid-cols-2 gap-4"><div><Label>Genre</Label><Input className="mt-1.5" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/></div><div><Label>Publication year</Label><Input type="number" className="mt-1.5" value={form.publication_year} onChange={e=>setForm({...form,publication_year:e.target.value})}/></div></div><div><Label>ISBN</Label><Input className="mt-1.5" value={form.isbn} onChange={e=>setForm({...form,isbn:e.target.value})}/></div><DialogFooter><Button disabled={saving} className="bg-green text-white">{saving&&<Loader2 className="w-4 h-4 mr-2 animate-spin"/>}Save</Button></DialogFooter></form></DialogContent></Dialog>
 <AlertDialog open={!!deleteId} onOpenChange={o=>!o&&setDeleteId(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle className="font-serif text-xl">Delete book?</AlertDialogTitle><AlertDialogDescription>This removes the title and its active inventory records.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="px-4 py-2 border border-line rounded-sm">Cancel</AlertDialogCancel><AlertDialogAction onClick={del} className="bg-[#9A2B2B] text-white px-4 py-2 rounded-sm">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
