import { useEffect, useState } from "react";
import api, { formatApiErrorDetail } from "../../lib/api";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "../../components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import StatusBadge from "../../components/StatusBadge";
import { Plus, Trash2, Loader2 } from "lucide-react";
import { toast } from "sonner";
export default function Inventory(){
 const [inv,setInv]=useState([]),[books,setBooks]=useState([]),[libs,setLibs]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const [i,b,l]=await Promise.all([api.get("/inventory"),api.get("/books"),api.get("/libraries")]);setInv(i.data);setBooks(b.data);setLibs(l.data)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setSaving(true);try{await api.post("/inventory",{library_id:form.library_id,book_id:form.book_id,total_copies:parseInt(form.total_copies,10),available_copies:parseInt(form.available_copies,10)});toast.success("Inventory saved");setOpen(false);setForm(EMPTY);load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}finally{setSaving(false)}};
 const remove=async(a,b)=>{try{await api.delete("/inventory",{params:{library_id:a,book_id:b}});toast.success("Removed from inventory");load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}};
 const status=it=>it.total_copies<=0?"Not Available":it.available_copies>0?"Available":"Borrowed";
 return <div><div className="flex items-center justify-between mb-8"><div><p className="text-gold uppercase tracking-widest text-xs mb-2">Manage</p><h1 className="font-serif text-4xl font-bold">Inventory</h1></div><Button onClick={()=>{setForm(EMPTY);setOpen(true)}} disabled={!books.length||!libs.length} data-testid="add-inventory-btn" className="bg-green text-white"><Plus className="w-4 h-4 mr-2"/>Add stock</Button></div>
 {(!books.length||!libs.length)&&!loading&&<p className="mb-6 text-sm text-gold bg-[#FFF4E5] border border-line rounded-sm px-4 py-3">Add at least one library and one book before managing inventory.</p>}
 {loading?<div className="flex gap-2 text-muted"><Loader2 className="animate-spin"/>Loading…</div>:!inv.length?<div className="text-center py-16 border border-dashed border-line text-muted">No stock recorded yet.</div>:<div className="border border-line rounded-sm bg-white overflow-hidden"><Table><TableHeader><TableRow className="bg-surface"><TableHead>Book</TableHead><TableHead>Library</TableHead><TableHead>Total</TableHead><TableHead>Available</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{inv.map((it,i)=><TableRow key={i} data-testid="inventory-row"><TableCell className="py-4 font-medium">{it.book?.title||"—"}</TableCell><TableCell className="py-4 text-muted">{it.library?.name||"—"}</TableCell><TableCell className="py-4 text-muted">{it.total_copies}</TableCell><TableCell className="py-4 text-muted">{it.available_copies}</TableCell><TableCell className="py-4"><StatusBadge status={status(it)} count={status(it)==="Borrowed"?it.total_copies-it.available_copies:it.available_copies}/></TableCell><TableCell className="py-4 text-right"><button onClick={()=>remove(it.library_id,it.book_id)} data-testid="delete-inventory-btn" className="p-1.5 text-[#9A2B2B]"><Trash2 className="w-4 h-4"/></button></TableCell></TableRow>)}</TableBody></Table></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Add / update stock</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div><Label>Book</Label><Select value={form.book_id} onValueChange={v=>setForm({...form,book_id:v})}><SelectTrigger className="mt-1.5" data-testid="inventory-book-select"><SelectValue placeholder="Select a book"/></SelectTrigger><SelectContent>{books.map(b=><SelectItem key={b.id} value={b.id}>{b.title}</SelectItem>)}</SelectContent></Select></div><div><Label>Library</Label><Select value={form.library_id} onValueChange={v=>setForm({...form,library_id:v})}><SelectTrigger className="mt-1.5" data-testid="inventory-library-select"><SelectValue placeholder="Select a library"/></SelectTrigger><SelectContent>{libs.map(l=><SelectItem key={l.id} value={l.id}>{l.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-4"><div><Label>Total copies</Label><Input type="number" min="0" className="mt-1.5" value={form.total_copies} onChange={e=>setForm({...form,total_copies:e.target.value})} required data-testid="inventory-total-input"/></div><div><Label>Available copies</Label><Input type="number" min="0" className="mt-1.5" value={form.available_copies} onChange={e=>setForm({...form,available_copies:e.target.value})} required data-testid="inventory-available-input"/></div></div><DialogFooter><Button type="submit" disabled={saving||!form.book_id||!form.library_id} className="bg-green text-white" data-testid="save-inventory-btn">{saving&&<Loader2 className="w-4 h-4 mr-2 animate-spin"/>}Save</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
