import { useEffect, useState } from "react";
import api,{formatApiErrorDetail} from "@/lib/api";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Label} from "@/components/ui/label";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "@/components/ui/alert-dialog";
import {Plus,Pencil,Trash2,MapPin,Phone,Mail,Loader2} from "lucide-react"; import {toast} from "sonner";
const EMPTY={name:"",address:"",phone:"",email:""};
export default function Libraries(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[editId,setEditId]=useState(null),[saving,setSaving]=useState(false),[deleteId,setDeleteId]=useState(null);
 const load=async()=>{setLoading(true);try{setItems((await api.get("/libraries")).data)}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setSaving(true);try{if(editId){await api.put(`/libraries/${editId}`,form);toast.success("Library updated")}else{await api.post("/libraries",form);toast.success("Library added")}setOpen(false);load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}finally{setSaving(false)}};
 const confirmDelete=async()=>{try{await api.delete(`/libraries/${deleteId}`);toast.success("Library deleted");load()}catch(err){toast.error(formatApiErrorDetail(err.response?.data?.detail)||err.message)}finally{setDeleteId(null)}};
 return <div><div className="flex items-center justify-between mb-8"><div><p className="text-gold uppercase tracking-widest text-xs mb-2">Manage</p><h1 className="font-serif text-4xl font-bold">Libraries</h1></div><Button onClick={()=>{setForm(EMPTY);setEditId(null);setOpen(true)}} data-testid="add-library-btn" className="bg-green hover:bg-green-dark text-white"><Plus className="w-4 h-4 mr-2"/>Add library</Button></div>
 {loading?<div className="flex gap-2 text-muted"><Loader2 className="animate-spin"/>Loading…</div>:items.length===0?<div className="text-center py-16 border border-dashed border-line text-muted">No libraries yet. Add your first branch.</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">{items.map(lib=><div key={lib.id} className="bg-white border border-line p-6 rounded-sm" data-testid="library-card"><div className="flex justify-between gap-3"><h3 className="font-serif text-xl font-bold">{lib.name}</h3><div className="flex gap-1"><button onClick={()=>{setForm({name:lib.name,address:lib.address,phone:lib.phone||"",email:lib.email||""});setEditId(lib.id);setOpen(true)}} data-testid="edit-library-btn" className="p-1.5 text-green hover:bg-[#EAF3EB]"><Pencil className="w-4 h-4"/></button><button onClick={()=>setDeleteId(lib.id)} data-testid="delete-library-btn" className="p-1.5 text-[#9A2B2B] hover:bg-[#FBEBEA]"><Trash2 className="w-4 h-4"/></button></div></div><div className="mt-4 space-y-2 text-sm text-muted"><p className="flex gap-2"><MapPin className="w-4 h-4 text-green"/>{lib.address}</p>{lib.phone&&<p className="flex gap-2"><Phone className="w-4 h-4 text-green"/>{lib.phone}</p>}{lib.email&&<p className="flex gap-2"><Mail className="w-4 h-4 text-green"/>{lib.email}</p>}</div></div>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">{editId?"Edit library":"Add library"}</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div><Label>Name</Label><Input className="mt-1.5" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required data-testid="library-name-input"/></div><div><Label>Address</Label><Input className="mt-1.5" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required data-testid="library-address-input"/></div><div className="grid grid-cols-2 gap-4"><div><Label>Phone</Label><Input className="mt-1.5" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><Label>Email</Label><Input className="mt-1.5" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></div><DialogFooter><Button disabled={saving} className="bg-green text-white">{saving&&<Loader2 className="w-4 h-4 mr-2 animate-spin"/>}Save</Button></DialogFooter></form></DialogContent></Dialog>
 <AlertDialog open={!!deleteId} onOpenChange={o=>!o&&setDeleteId(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle className="font-serif text-xl">Delete library?</AlertDialogTitle><AlertDialogDescription>This also removes its inventory from the active catalogue.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="px-4 py-2 border border-line rounded-sm">Cancel</AlertDialogCancel><AlertDialogAction onClick={confirmDelete} className="bg-[#9A2B2B] text-white px-4 py-2 rounded-sm">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
